version: 0.2

phases:
  install:
    commands:
      # Install Terraform CLI
      - curl -L https://releases.hashicorp.com -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - rm terraform.zip

  pre_build:
    commands:
      - echo "Checking Terraform version..."
      - terraform version
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Creating Terraform plan..."
      - terraform plan -out=tfplan.binary

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan.binary
      - echo "Terraform apply complete!"

