version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum install terraform  

pre_build:
    commands:
      - echo "Checking Terraform version..."
      - terraform version
      - echo "Initializing Terraform..."
      - terraform init

build:
    commands:
      - echo "Creating Terraform plan..."
      - terraform plan -out=tfplan.binary

post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve tfplan.binary
      - echo "Terraform apply complete!"

